// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXf9X-5PsSFxvfnQDpUGMXJkrLndNcUU',
    appId: '1:1014439239877:web:3770fae04d6cbe096810ac',
    messagingSenderId: '1014439239877',
    projectId: 'krainet-task-93d29',
    authDomain: 'krainet-task-93d29.firebaseapp.com',
    storageBucket: 'krainet-task-93d29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_N5DyZY-xz5soe9z-sTqg3ftyYQ8ZAoc',
    appId: '1:1014439239877:android:c9f00dd35360285f6810ac',
    messagingSenderId: '1014439239877',
    projectId: 'krainet-task-93d29',
    storageBucket: 'krainet-task-93d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLTcxtjhadb5d2Y2aoY8-zjIFJGJACl0',
    appId: '1:1014439239877:ios:e12c04e727d9f2fb6810ac',
    messagingSenderId: '1014439239877',
    projectId: 'krainet-task-93d29',
    storageBucket: 'krainet-task-93d29.appspot.com',
    iosClientId: '1014439239877-dfhqqc2718cluef59632gkkhdao5ad03.apps.googleusercontent.com',
    iosBundleId: 'com.example.krainetTask',
  );
}
